version: 1
disable_existing_loggers: True
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
    stream  : ext://sys.stdout
formatters:
  brief:
    format: '%(message)s'
  default:
    format: '{asctime} [{levelname}] ({processName:s}/{threadName:s}) - {name} - {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'
loggers:
  root:
    handlers: [console]
    level: INFO